# Generated by Django 3.2.6 on 2021-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio_perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('subrogado', models.BooleanField(default=False)),
                ('grupo', models.CharField(choices=[('Biologia molecular', 'Biologia molecular'), ('Inmunoligia', 'Inmunoligia'), ('Uroanalisi y Coprologia', 'Uroanalisi y Coprologia'), ('Hematologia y coagulacion', 'Hematologia y coagulacion'), ('Microbiologia', 'Microbiologia'), ('Anatomia y Patologia', 'Anatomia y Patologia'), ('Hemostasia', 'Hemostasia')], max_length=100)),
                ('contenedor', models.CharField(choices=[('Amarillo', '01'), ('Dorado', '04'), ('Azul', '03'), ('Verde', '05'), ('Rojo', '06'), ('Morado', '02'), ('Caja de Petri', '07'), ('Culturete', '08'), ('Frasco con Formol', '09'), ('Frasco esteril', '010'), ('Frasco con aditivo', '011'), ('Frasco con medio de Michel', '012'), ('Exudado', '013'), ('Hisopo', '014'), ('Frasco PCR', '015'), ('Transporte', '016'), ('Laminilla', '017'), ('Jeringa', '018'), ('Trampa', '019'), ('Frotis', '020'), ('Medio para hemocultivo', '021'), ('Contenedor de heces fecales', '022')], max_length=100)),
                ('metodo', models.CharField(max_length=100)),
                ('tipo_muestra', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('indicaciones', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estudios Y perfiles',
                'managed': True,
            },
        ),
    ]
