# Generated by Django 3.2.6 on 2021-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio_perfil',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Ambos', 'Ambos')], default='Ambos', max_length=10),
        ),
    ]
