# Generated by Django 3.2.6 on 2021-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio_perfil',
            name='Nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
