# Generated by Django 3.2.6 on 2021-09-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condiciones',
            table='Condiciones',
        ),
    ]
