# Generated by Django 3.2.6 on 2021-09-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_perfil', '0002_alter_condiciones_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condiciones',
            name='Clave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudio_perfil.estudio_perfil'),
        ),
    ]
