# Generated by Django 3.2.6 on 2021-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_perfil', '0002_estudio_perfil_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio_perfil',
            name='contenedor',
            field=models.CharField(choices=[('Amarillo', 'Amarillo'), ('Dorado', 'Dorado'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Rojo', 'Rojo'), ('Morado', 'Morado'), ('Caja de Petri', 'Caja de Petri'), ('Culturete', 'Culturete'), ('Frasco con Formol', 'Frasco con Formol'), ('Frasco esteril', 'Frasco esteril'), ('Frasco con aditivo', 'Frasco con aditivo'), ('Frasco con medio de Michel', 'Frasco con medio de Michel'), ('Exudado', 'Exudado'), ('Hisopo', 'Hisopo'), ('Frasco PCR', 'Frasco PCR'), ('Transporte', 'Transporte'), ('Laminilla', 'Laminilla'), ('Jeringa', 'Jeringa'), ('Trampa', 'Trampa'), ('Frotis', 'Frotis'), ('Medio para hemocultivo', 'Medio para hemocultivo'), ('Contenedor de heces fecales', 'Contenedor de heces fecales')], max_length=100),
        ),
    ]
